If:                               # Apply this config conditionally
  PathMatch: .*\.h                # to all headers...
  PathExclude: include/llvm-c/.*  # except those under include/llvm-c/

CompileFlags:                     # Tweak the parse settings
  Add: [-Wall]             # treat all files as C++, enable more warnings
  Remove: [-W*]                     # strip all other warning-related flags
  Compiler: gcc 
  BuiltinHeaders: QueryDriver

Index:
  Background: Skip
  StandardLibrary: true

Completion:
  AllScopes: Yes
  ArgumentLists: FullPlaceholders
  HeaderInsertion: IWYU
  CodePatterns: All

Diagnostics:
  ClangTidy:
    FastCheckFilter: Strict
  UnusedIncludes: Strict
